from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.models import Report


def generate_markdown(report: Report) -> str:
    categories = json.loads(report.category_breakdown) if report.category_breakdown else []
    rules = json.loads(report.rules) if report.rules else []
    recommendations = json.loads(report.recommendations) if report.recommendations else []

    total_rules = len(rules)
    passed_rules = sum(1 for r in rules if r.get("passed", False))
    failed_rules = total_rules - passed_rules

    lines: list[str] = []
    lines.append(f"# Repository Health Report: {report.repo_full_name}")
    lines.append("")
    lines.append(f"**Repository:** [{report.repo_full_name}]({report.repo_url})")
    lines.append(f"**Overall Score:** {report.score}/100 (Grade: {report.grade})")
    lines.append(f"**Commit:** `{report.commit_sha}`")
    lines.append(f"**Generated:** {report.created_at}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Overall Score | {report.score}% |")
    lines.append(f"| Grade | {report.grade} |")
    lines.append(f"| Passed Rules | {passed_rules} |")
    lines.append(f"| Failed Rules | {failed_rules} |")
    lines.append(f"| Total Rules | {total_rules} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Category Breakdown")
    lines.append("")

    for cat in categories:
        cat_score = cat.get("score", 0)
        cat_max = cat.get("max_score", 0)
        cat_pct = round(cat_score / cat_max * 100, 1) if cat_max > 0 else 0
        lines.append(f"### {cat.get('name', 'Unknown')} ({cat_pct}%)")
        lines.append("")
        lines.append(f"Score: {cat_score}/{cat_max}")
        lines.append("")

        details = cat.get("details", [])
        if details:
            lines.append("| Rule | Status | Severity | Evidence |")
            lines.append("|------|--------|----------|----------|")
            for d in details:
                if isinstance(d, dict):
                    rule_id = d.get("rule", "unknown")
                    status = d.get("status", "?")
                    severity = d.get("severity", "medium")
                    evidence = d.get("evidence", "")
                    lines.append(f"| {rule_id} | {status} | {severity} | {evidence} |")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Recommendations")
    lines.append("")

    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            msg = rec.get("message", rec.get("recommendation", "")) if isinstance(rec, dict) else str(rec)
            lines.append(f"{i}. {msg}")
    else:
        lines.append("No recommendations. Great job!")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by RepoDoctor v0.1.0*")

    return "\n".join(lines)
