from __future__ import annotations

import json
from typing import TYPE_CHECKING

from fpdf import FPDF
from fpdf.enums import XPos, YPos

if TYPE_CHECKING:
    from app.models.models import Report


class ReportPDF(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "RepoDoctor Report", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf(report: Report) -> bytes:
    categories = json.loads(report.category_breakdown) if report.category_breakdown else []
    rules = json.loads(report.rules) if report.rules else []
    recommendations = json.loads(report.recommendations) if report.recommendations else []

    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    effective_width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "Repository Health Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 7, f"Repository: {report.repo_full_name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 7, f"URL: {report.repo_url}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 7, f"Commit: {report.commit_sha}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 7, f"Generated: {report.created_at}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    total_rules = len(rules)
    passed_rules = sum(1 for r in rules if r.get("passed", False))
    failed_rules = total_rules - passed_rules

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 7, f"Overall Score: {report.score}/100 (Grade: {report.grade})", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(
        0,
        7,
        f"Passed Rules: {passed_rules} | Failed Rules: {failed_rules} | Total: {total_rules}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
    )
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Category Breakdown", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    for cat in categories:
        cat_name = cat.get("name", "Unknown")
        cat_score = cat.get("score", 0)
        cat_max = cat.get("max_score", 0)
        cat_pct = round(cat_score / cat_max * 100, 1) if cat_max > 0 else 0

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(0, 8, f"{cat_name} - {cat_pct}% ({cat_score}/{cat_max})", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        details = cat.get("details", [])
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        for d in details:
            if isinstance(d, dict):
                rule_id = d.get("rule", "unknown")
                status = d.get("status", "?")
                evidence = str(d.get("evidence", ""))
                line = f"  [{status}] {rule_id}: {evidence}"
                if len(line) > 90:
                    line = line[:87] + "..."
                pdf.multi_cell(effective_width, 5, line)
        pdf.ln(4)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Recommendations", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            msg = rec.get("message", rec.get("recommendation", "")) if isinstance(rec, dict) else str(rec)
            if len(msg) > 100:
                msg = msg[:97] + "..."
            pdf.multi_cell(effective_width, 6, f"{i}. {msg}")
            pdf.ln(2)
    else:
        pdf.cell(0, 7, "No recommendations. Great job!", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y() + 4, 200, pdf.get_y() + 4)
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by RepoDoctor v0.1.0", align="C")

    return bytes(pdf.output())
